name: EasyRule
version: '1.0.0'
main: com.ekedata.easyrule.EasyRule
api-version: '1.20'

commands:
  easyrule:
    aliases:
      - "er"
      - "easy""
    description: Manage game rules easily
    usage: /easyrule <规则名称> <true|false>